SECRET_KEY_ACCESS = 'gunshopthammasatuniversity'
SECRET_KEY_ACTIVATION = 'pleaseactivateyouraccout'
ALGORITHM = 'HS256'
ADMIN_DOMAIN = "@dome.tu.ac.th"
ACCESS_TOKEN_EXPIRE_MINUTES = 1000
ACTIVATION_TOKEN_EXPIRE_MINUTES = 1000
SENDER_EMAIL = 'khlaisuwanviphava@gmail.com'
APP_PASSWORD = "eekf hgvo zzat ixdh"
LINK = "http://127.0.0.1:8000"
HOST_DB = "mysql"
USER_DB = 'user'
PASSWORD_DB = 'password'
DATABASE = 'db'
