version: "3.8"

services:
  authentication:
    build: ./auth_service/service/
    depends_on:
      - mysql
    working_dir: /usr/app/src
      
    volumes:
      - ./auth_service/service:/usr/app/src
    ports:
      - '8000:8000'

  product:
    build: ./product_service/service/
    depends_on:
      - mysql
    working_dir: /usr/app/src
      
    volumes:
      - ./product_service/service:/usr/app/src
    ports:
      - '8001:8000'

  order:
    build: ./order_service/service/
    depends_on:
      - mysql
      - product
    working_dir: /usr/app/src
      
    volumes:
      - ./order_service/service/:/usr/app/src
    ports:
      - '8002:8000'

  mysql:
    build: ./database/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '9000:3306'
